### ISSUE TITLE
Jazz2 SDL binary doesn't recognize DS4 controller properly 

### ISSUE THREAD

**Issue by xcom169** [deathkiller/jazz2-native#42] opened 2023-12-27 11:22 UTC
### Jazz² Resurrection version

2.4.0

### System information

Windows 10 or Arch Linux

### Issue description

When running the Jazz2 SDL binary the button mapping for DS4 completely upside-down. I can't even change it. 
With non-sdl binary it's working fine. 

### Steps to reproduce

Connect DS4 controller with USB or with Dongle.  
Run Jazz2 SDL and try to control the game.

**Comment by deathkiller** [comment] 2023-12-27 20:02
If GLFW build works good and SDL doesn't, it's probably something wrong with SDL (that's one of the reasons why I support both options). 
It can be caused by missing gamepad mapping. You can try to copy [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt) to `Content` directory. Or check the log if the correct mapping is loaded by the game.

**Comment by xcom169** [comment] 2023-12-28 12:42
I copied the file but it's still a little bit messy.  The buttons are mapped incorrectly. 
 Do you have a DS4 to try on your computer?


Log file:
void nCine::MainApplication::init(std::unique_ptr<nCine::IAppEventHandler> (*)(), int, char**) -> IAppEventHandler::OnPreInit() invoked
nCine::SdlInputManager::SdlInputManager() -> Joystick 0 "PS4 Controller" - 0 hats, 6 axes, 16 buttons, 0 balls
void nCine::JoyMapping::init(const nCine::IInputManager*) -> Found 349 mappings in 349 lines
bool nCine::JoyMapping::onJoyConnected(const nCine::JoyConnectionEvent&) -> Joystick mapping found for "PS4 Controller" [03008fe54c050000a00b000000016800] (0)
void nCine::Application::initCommon() -> Jazz² Resurrection v2.4.1 initializing...


void nCine::Application::initCommon() -> IAppEventHandler::OnInit() invoked
static void nCine::SdlInputManager::handleJoyDeviceEvent(const SDL_Event&) -> Joystick 0 "PS4 Controller" (03008fe54c050000a00b000000016800) has been connected - 0 hats, 6 axes, 16 buttons, 0 balls
bool nCine::JoyMapping::onJoyConnected(const nCine::JoyConnectionEvent&) -> Joystick mapping found for "PS4 Controller" [03008fe54c050000a00b000000016800] (0)
void Death::IO::FileStream::Open(Death::IO::FileAccessMode) -> File "Cache/Tilesets/xmas2.j2t" opened
virtual void Death::IO::FileStream::Close() -> File "Cache/Tilesets/xmas2.j2t" closed
void Death::IO::FileStream::Open(Death::IO::FileAccessMode) -> File "Content/Metadata/UI/MainMenu.res" opened
void Death::IO::FileStream::Open(Death::IO::FileAccessMode) -> File "Content/Animations/UI/logo.aura" opened

**Comment by deathkiller** [comment] 2023-12-28 13:16
So it seems the mapping is not corrent. The only option is probably to modify it. Unfortunately, I don't have any PS controllers (only Xbox ones).

**Comment by deathkiller** [comment] 2024-01-02 09:51
Because I can't fix and test this one myself (and it works fine with GLFW), I'm going to close this issue. I would accept donations for DualSense controller to add proper support for it, but DS4 controller is already very old and probably end of official support very soon. Feel free to reopen it if you have any ideas for this issue.

**Closed by deathkiller** 2024-01-02 09:51 UTC
Labels: wontfix, 3rd-party bug
