### ISSUE TITLE
1.0.0 Game is not responding on Nvidia Shield TV

### ISSUE THREAD

**Issue by bartekczajkowski** [deathkiller/jazz2-native#2] opened 2022-10-08 21:34 UTC
Hi,
On Nvidia shield TV (android tv): after cinematics - game ignores input from:
- remote (as previous 0.7.2)
- bluetooth pad (ps4 dual shock)
- usb pad (some logitech)

i'm stuck on first item of main menu.

Dual shock worked fine on previous version

**Comment by deathkiller** [comment] 2022-10-09 10:49
It uses completely different libraries for input handling now, I will try to find out what's wrong and fix it soon.

**Comment by deathkiller** [comment] 2022-10-31 08:46
It should be fixed in the latest commit 5f95118ce87297433be343d758b909516a5c78be.

**Comment by bartekczajkowski** [comment] 2022-11-15 20:41
Hi,
No response on 1.1.0 either - do you want/need any additional info?

**Comment by deathkiller** [comment] 2022-11-16 11:12
It still doesn't work for you? That's strange, it should work now.

**Comment by bartekczajkowski** [comment] 2022-11-16 19:26
Yes, no response on shield 2019 with latest firmware on paired ps4 dualshock. Also no response to shield remote (but not sure is any is expected - maybe at least at menu?)

**Comment by deathkiller** [comment] 2022-11-17 14:15
And do you have any input/controller that is working? So maybe I can prepare some menu with diagnostics information. I can't reproduce it here.

**Comment by fehmi1907** [comment] 2023-06-04 17:21
I experience the same issue on my Nvidia Shield Pro 2019. Tried with several different controllers but no avail. Below is from the log file; please let me know if you need further details.

```
[W] static void nCine::AndroidInputManager::initAccelerometerSensor(android_app *) -> No accelerometer sensor available
[I] void nCine::JoyMapping::init(const nCine::IInputManager *) -> Parsed 73 strings for 73 mappings
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (3, 0) - Buttons 0:96 1:97 -1:98 2:99 3:100 -1:101 9:102 10:103 -1:104 -1:105
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (3, 0) - D-Pad not detected
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (3, 0) - Axis hats not detected
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (3, 0) - Axes 0:0 (-1.00 to 1.00) 1:1 (-1.00 to 1.00)
[I] static int nCine::AndroidInputManager::findJoyId(int) -> Device 3, "Sony Interactive Entertainment Controller" (050000004c050000da0c00000f860300), has been connected as joystick 0 - 2 axes, 10 buttons
[I] bool nCine::JoyMapping::onJoyConnected(const nCine::JoyConnectionEvent &) -> Joystick mapping not found for "Sony Interactive Entertainment Controller" [050000004c050000da0c00000f860300] (0), using Android default mapping
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (5, 1) - Buttons 0:96 1:97 2:99 3:100 9:102 10:103 7:106 8:107 6:108 4:109 5:110
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (5, 1) - D-Pad not detected
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (5, 1) - Axes 0:0 (-1.00 to 1.00) 1:1 (-1.00 to 1.00) 2:11 (-1.00 to 1.00) 3:14 (-1.00 to 1.00) 4:17 (0.00 to 1.00) 5:18 (0.00 to 1.00) 6:23 (0.00 to 1.00) 7:22 (0.00 to 1.00) 8:15 (-1.00 to 1.00) 9:16 (-1.00 to 1.00)
[I] static int nCine::AndroidInputManager::findJoyId(int) -> Device 5, "Microsoft X-Box 360 pad" (050000005e0400008e020000ff7f3f00), has been connected as joystick 1 - 10 axes, 11 buttons
[I] bool nCine::JoyMapping::onJoyConnected(const nCine::JoyConnectionEvent &) -> Joystick mapping not found for "Microsoft X-Box 360 pad" [050000005e0400008e020000ff7f3f00] (1), using Android default mapping
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (6, 2) - Buttons 0:96 1:97 2:99 3:100 4:4
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (6, 2) - Axis hats not detected
[I] static void nCine::AndroidInputManager::deviceInfo(int, int) -> Device (6, 2) - Axes
[I] static int nCine::AndroidInputManager::findJoyId(int) -> Device 6, "virtual-search" (05000000d1180000000100000f780000), has been connected as joystick 2 - 0 axes, 5 buttons
[I] bool nCine::JoyMapping::onJoyConnected(const nCine::JoyConnectionEvent &) -> Joystick mapping not found for "virtual-search" [05000000d1180000000100000f780000] (2), using Android default mapping
```

**Comment by deathkiller** [comment] 2023-06-04 17:34
You can check new menu section in Options > Controls > Input Diagnostics. It should show you which buttons and axes you are pressing.

**Comment by fehmi1907** [comment] 2023-06-04 17:47
My problem is that I cannot navigate at all through the menus; no inputs are detected. I connected a keyboard, mouse, wired Xbox controllers, PlayStation Classic controller, Sega Saturn USB controller but Jazz did not respond to any of these.

I know you recently overhauled the input system but when I was previously on 0.7.3, any controller worked perfectly.

**Comment by deathkiller** [comment] 2023-06-04 19:35
But according to the log, some controllers are detected, so it should work. I don't know how to investigate/fix it without debugger.

**Comment by fehmi1907** [comment] 2023-06-04 20:15
Every controller I plugged in had a log entry:

- Wired controllers: Xbox 360, PlayStation Classic, Sega Saturn, Hori Fighting Commander 4
- Bluetooth: Xbox Series Controller
- Adapter: 8bitdo USB Adapter v2

However, no button presses were detected. I also plugged in a keyboard and a mouse but these did not work either.

I believe this is hard to investigate if you do not have an Android TV device. Would you be able to implement a way to navigate through the menus via an alternate method (like keyboard & mouse)? 

Obviously, I cannot use a touchscreen to navigate but Nvidia Shield also has a mobile app which simulates touch controls. I also tried this but it did not work on the menus.

**Comment by deathkiller** [comment] 2023-06-04 22:17
Keyboard support should be already there (and mouse is not supported). If you are not able to do anything then it's some critical issue, so the new debug menu is useless anyway. Maybe I will try to add some more debug messages to log, so we can check what's happening.

**Comment by fehmi1907** [comment] 2023-06-04 23:42
Appreciate that you're looking into this. Happy to help you debug.

**Comment by deathkiller** [comment] 2023-06-05 20:03
I added `Jazz2_Android_DEBUG_ARM` build to GitHub Actions, you can install it, then you can press some buttons and everything should be written in the log. You can start with pressing only directional buttons, then you can try some more button, so we can analyze the log easily.

**Comment by fehmi1907** [comment] 2023-06-05 20:39
Please see below:
[https://www.dropbox.com/s/50pvvwgjfkv3crw/Jazz2.log?dl=0](url)

I had two controllers connected, Xbox controller and Sega Saturn. I started with the Xbox one and pressed all buttons (first dpad) and moved all analog sticks. I did the same for Saturn one.

Please advise if this is something you can work with. If not, I will use one controller at a time.

**Comment by deathkiller** [comment] 2023-06-05 21:16
Can you try the latest version, please? I see there are some internal NVIDIA Shield controllers, so I disabled them. Everything else looks good.

**Comment by fehmi1907** [comment] 2023-06-05 21:41
The latest regular ARM version works perfect; thanks for the super quick fix!

**Comment by deathkiller** [comment] 2023-06-05 21:43
So the NVIDIA Shield mystery is solved, thanks!

**Closed by deathkiller** 2023-06-05 21:43 UTC
Labels: bug
