### ISSUE TITLE
Build fails with OPENGLES1_gl_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by myself600** [deathkiller/jazz2-native#18] opened 2022-12-17 08:56 UTC
The newest revision no longer builds:

> -- Found system OpenGL ES 2 library: /usr/lib/libGLESv2.so;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libGLESv2.so;OPENGLES1_gl_LIBRARY-NOTFOUND
...
[100%] Linking CXX executable jazz2
/bin/ld: cannot find /usr/lib/libGLESv2.so;/usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libGLESv2.so;OPENGLES1_gl_LIBRARY-NOTFOUND: Adresár alebo súbor neexistuje
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/jazz2.dir/build.make:4345: jazz2] Error 1
make[2]: Leaving directory '/var/tmp/pamac-build-pbpro/jazz2-git/src/Jazz2-LinuxGcc-Release'
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/jazz2.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/pamac-build-pbpro/jazz2-git/src/Jazz2-LinuxGcc-Release'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/var/tmp/pamac-build-pbpro/jazz2-git/src/Jazz2-LinuxGcc-Release'

### Attachments:
[jazz2_build.log](https://github.com/deathkiller/jazz2-native/files/10251340/jazz2_build.log)

**Comment by deathkiller** [comment] 2022-12-17 10:27
Sorry, hopefully it should be fixed now. Let me know. `FindOpenGLES2.cmake` file should be definitely rewritten, but I can't test it myself.

**Comment by myself600** [comment] 2022-12-17 12:43
It doesn't:

> -- Found system OpenGL ES 2 library: /usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libGLESv2.so
...
[100%] Linking CXX executable jazz2
/bin/ld: cannot find /usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libGLESv2.so: Adresár alebo súbor neexistuje
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/jazz2.dir/build.make:4345: jazz2] Error 1
make[2]: Leaving directory '/var/tmp/pamac-build-pbpro/jazz2-git/src/Jazz2-LinuxGcc-Release'
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/jazz2.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/pamac-build-pbpro/jazz2-git/src/Jazz2-LinuxGcc-Release'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/var/tmp/pamac-build-pbpro/jazz2-git/src/Jazz2-LinuxGcc-Release'

> [pbpro@manjaro-arm ~]$ ls /usr/lib/lib{SM,ICE,X11,Xext,GLESv2}.so
/usr/lib/libGLESv2.so  /usr/lib/libICE.so  /usr/lib/libSM.so  /usr/lib/libX11.so  /usr/lib/libXext.so

:man_shrugging: The latest version of Jazz² Resurrection on my system is `v1.3.r239-bbb128f`

### Attachments:

[jazz2_build2.log](https://github.com/deathkiller/jazz2-native/files/10251666/jazz2_build2.log)

**Comment by myself600** [comment] 2022-12-17 14:12
OPENGLES1_gl_LIBRARY-NOTFOUND wasn't the problem afterall ([jazz2_build2.log](https://github.com/deathkiller/jazz2-native/files/10251666/jazz2_build2.log)). Reversing https://github.com/deathkiller/jazz2-native/commit/5833d6cd6bcb6ea2a891963cf4ff9f5e5138ec16 fixes the issue.

**Comment by deathkiller** [comment] 2022-12-17 14:20
Yes, I think it's caused by double quotes added here: https://github.com/deathkiller/jazz2-native/blob/master/cmake/ncine_imported_targets.cmake#L552
But I don't know why, can you try to remove them? I can't reproduce it here.

**Comment by myself600** [comment] 2022-12-17 14:47
Worked! Also,

> Sorry, hopefully it should be fixed now. Let me know. `FindOpenGLES2.cmake` file should be definitely rewritten, but I can't test it myself.

Tbh, I should have tried the release first, but it didn't occurred to me and I assumed the Git version should build as usual...

**Closed** 2022-12-17 14:48 UTC

**Comment by deathkiller** [comment] 2022-12-17 20:06
I added `aarch64` to GitHub Actions and found the same error. It should be fixed now.

**Comment by myself600** [comment] 2022-12-18 21:11
...and I have merged this into a new PKGBUILD :smile: . It will omit compilation times and build failures like this one.

**Comment by deathkiller** [comment] 2022-12-18 21:43
I haven't seen the PKGBUILD, but if you are using any of `Build*` files located in repo root, please use CMake directly instead and define CMake parameters as appropriate (you can take a look at GitHub Actions - e.g., https://github.com/deathkiller/jazz2-native/blob/master/.github/workflows/linux_cc.yml). I will probably remove these files in the future, because it's too unflexible and not used by me at all anymore.

Jinak slovenština mi jde o trochu líp než angličtina, takže pro snížení reakční doby bych se úplně nezlobil, kdybysme z GitHubu přešli na Discord. 😀
